### ISSUE TITLE
Sub To Motion Detect Events

### ISSUE THREAD

**Issue by jmswenski** [jeffreydwalter/arlo#16]
Hi Jeff,

I came across your repo for arlo. Good stuff! I just purchased one of these systems (a big aspect of the decision was that it looked like there was a project out there that someone was hacking with) I was wondering if you knew how to subscribe to motion detection events or if that was possible. If you could point me in the right direction, I would gladly contribute anything I came up with to your repo. 

Cheers mate,
JS

**Comment by jeffreydwalter** [comment]
Hi Jason (@jmswenski), thanks for the kind words!

I don't currently know if it's possible to subscribe to a motion event. The UI definitely seems to be aware of them because it toggles the little orange "motion" icon. The odd thing is that I don't see any network activity in the browser when motion is detected. I'll dig into it a bit more in the coming days and see if I can figure it out.

**Comment by patyork** [comment]
@jmswenski @jeffreydwalter Motion detection causes  an event, which will hit the EventStream which you can `.Subscribe()` to. However, the EventStream will eventually pause due to the standard "logged out for inactivity" metaphor (that also occurs in the web dashboard). The motion event will look something like:

```
event = {u'action': u'is', u'resource': u'cameras/4WA16B7M72***', u'transId': u'48946B7GA***!41***92!1503***739902', u'from': u'48946B7GA9***', u'properties': {u'motionDetected': True}}
```

with the `u'properties': {u'motionDetected': True}` part being the most important.

Ideally there would be a thread that would keep the authentication alive, but the EventStream as it sits, is good for at least 10 minutes.

**Comment by jeffreydwalter** [comment]
Thanks for the reply @patyork! Makes perfect sense. :)

I'm actually working on a full rewrite of this library. This code base was a weekend hack I put together to fill a void. Now that people are actually using it, I feel I owe the world a proper library. :) My plan is to provide a new more object-oriented API along with a backwards compatible API so existing code doesn't break. As part of that I will improve the EventStream stuff and add some keep-alive code.

@jmswenski I added a new method `def SubscribeToMotionEvents(self, basestation_id, xcloud_id, callback)` to facilitate listening for motion detection events.

To use it you would do something like: 
```
arlo = Arlo(USERNAME, PASSWORD)

basestations = [ device for device in arlo.GetDevices() if device['deviceType'] == 'basestation' ]
device_id = basestations[0]['deviceId']
xcloud_id = basestations[0]['xCloudId']

def callback(arlo, device_id, xcloud_id, event):
    print("motion event detected!")
    # Here you will have access to self, basestation_id, xcloud_id, and the event schema.

arlo.SubscribeToMotionEvents(device_id, xcloud_id, callback)
```

Thanks,
Jeff

**Comment by jeffreydwalter** [comment]
@jmswenski I refactored things a bit, so if you pull the master branch as of today, the API has changed slightly (for the better I hope).

Basically, the change is that the methods all take a "camera" or "basestation" instead of "basestation_id", "camera_id", "xcloud_id", etc. All of that data is actually part of the device schema, so the methods just get it for you.

That being said, the example I posted yesterday would change slightly to be like so:
```
arlo = Arlo(USERNAME, PASSWORD)

basestations = arlo.GetDevices('basestation')

def callback(arlo, basetstations[0], event):
    print("motion event detected!")
    # Here you will have access to self, basestation, and the event schema.

arlo.SubscribeToMotionEvents(basestation[0], callback)
```

There's also a more generic `HandleEvents()` method which is called by SubscribeToMotionEvents(). This new method can be used to handle ALL events produced by the event stream if you want. You'd just have something like a big switch statement for each event type in the callback that you pass.

```
def HandleEvents(self, basestation, callback, timeout=None)
```

**Comment by jmswenski** [comment]
Magic! Def going to play around with this this weekend!

**Comment by Anton-Schuster** [comment]
Hi Jeff, i tested the example with motion detection, but i cant get it to work. 
The callback is not triggered. Did i miss smth?

Thanks,
Toni

**Comment by jeffreydwalter** [comment]
Hey @phr0st, sorry for the delayed response. I fixed a bug in the sample code.

Please try it again: https://github.com/jeffreydwalter/arlo/wiki/Subscribe-to-Motion-Events

Basically, I had basestation instead of basestations[0]. Sorry about that!

**Comment by Anton-Schuster** [comment]
hi jeff, sorry but now i´m getting an syntax error: 
`def callback(arlo, basestations[0], event):
                                   ^
SyntaxError: invalid syntax
`

**Comment by jeffreydwalter** [comment]
@phr0st my apologies... I made the change in the wrong place. Please try the sample code now.

**Comment by jlt24** [comment]
I currently am using the arlo-download.py in a cron job to extend my storage :) but can't get the motion to work.  I'm new to python.  I too am have the problem nothing seems to happen when motion is detected.  It is more than likely something I'm doing wrong.  Can you explain to me the difference between the following?  

from Arlo.Arlo import Arlo
and
from Arlo import Arlo

Sorry for the basic question. but I get the following error if I use "from Arlo.Arlo import Arlo"  If I change it to "from Arlo import Arlo" it works but I don't see any event triggered.

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from Arlo.Arlo import Arlo
ImportError: No module named Arlo

**Comment by jeffreydwalter** [comment]
@jlt24 no worries. 

The Python import syntax is slightly convoluted... I highly recommend you read up on it here: https://docs.python.org/3/reference/import.html

Basically, the import syntax required depends on whether you are using a traditional Python package or a namespace. It also sorta depends on the folder structure of your project.

The inclusion of Arlo.Arlo was a copy/paste issue on my part. In my local environment I cloned this repository into a folder named `Arlo`, so I had to use Arlo.Arlo import Arlo to import the package.
I corrected the example code.

I just tested the example code and it works fine for me. Can you please tell me what type of Arlo devices you're using? Include your code (Please remove sensitive info). What happens when you run the code and trigger your camera with movement?

**Comment by Anton-Schuster** [comment]
Still the same problem for me. Even with the new example code no movement event is triggered. I just use the example code and changed the credentials. I think @jlt24 has the same problem.
I have the Netgear Arlo VMS3130-100EUS Smart Home Basestation with one Arlo HD cam.

**Comment by jlt24** [comment]
Hardware version of the basestation is VMB3010r2.  I have 5 cameras connected with a mixture of H7 and H11 HW versions (not pro).  

Thanks for the explanation of the import, make sense now.  The code I used was pretty much just a copy of your sample.  I just wanted to maintain your original copy so I could revert back if I messed it up.  When the code is running and I trigger a camera I don't think anything happens.  Not sure yet on the best way to debug python but it looks like the callback function is never called.

**Comment by jeffreydwalter** [comment]
@phr0st @jlt24 I just tested again by copy/pasting the sample code from the wiki and it works fine. I have the VMB3000 basestation with two Arlo 1st gen cameras.

Here's my script:
```
🍺  [508] jeff_walter@Thunderbolt:~/Code/github/arlo
$ cat ArloTest.py 

from Arlo import Arlo
import json

USERNAME = 'xxxxxxxxxxx'
PASSWORD = 'xxxxxxxxxxx'

try:

    # Instantiating the Arlo object automatically calls Login(),
    # which returns an oAuth token that gets cached.
    # Subsequent successful calls to login will update the oAuth token.
    arlo = Arlo(USERNAME, PASSWORD)
    # At this point you're logged into Arlo.

    # Get the list of devices and filter on device type to only get the basestation.
    # This will return an array which includes all of the basestation's associated metadata.
    basestations = arlo.GetDevices('basestation')

    # Define a callback function that will get called once for each motion event.
    def callback(arlo, basestation, event):
        # Here you will have access to self, the basestation JSON object, and the event schema.
        print("motion event detected!")
        #print(basestation)
	#print(event)
	#print(arlo)

    # Subscribe to motion events. This method blocks until the event stream is closed.
    # (You can close the event stream in the callback if you no longer want to listen for events.)
    arlo.SubscribeToMotionEvents(basestations[0], callback)
except Exception as e:
    print(e)
```
Here's what I see when I run it:
```
🍺  [505] jeff_walter@Thunderbolt:~/Code/github/arlo
$ python ArloTest.py 
motion event detected!
```

Do you have the lastest code? (run `git pull` command)
Can you paste me the list of all the python packages you have installed? (run the `pip freeze` command)
What OS are you running?

It's possible the structure of the JSON returned for the event is slightly different for the various hardware.

Please run this script, give it a second, then trigger motion on your camera. Give it another minute or so to propagate the motion event and paste the output here (feel free to obscure the ids in the json)
```
from Arlo import Arlo
import json

USERNAME = 'xxxxxxxxxxx'
PASSWORD = 'xxxxxxxxxxx'

def pp(data):
    print(json.dumps(data, indent=4, sort_keys=True))

arlo = Arlo(USERNAME, PASSWORD)

basestations = arlo.GetDevices('basestation')
cameras = arlo.GetDevices('camera')

def callback(arlo, basestation, event):
    pp(event)
    # Here you will have access to self, basestation_id, xcloud_id, and the event schema.

arlo.StartRecording(cameras[0])
arlo.HandleEvents(basestations[0], callback)
```

**Comment by Anton-Schuster** [comment]
hi @jeffreydwalter 
here is the output:
`pip3 freeze
chardet==2.3.0
colorama==0.3.2
html5lib==0.999
monotonic==1.4
requests==2.4.3
six==1.8.0
sseclient==0.0.18
urllib3==1.9.1
wheel==0.24.0`
and here is the output of the script:
`{
    "action": "is",
    "from": "xx",
    "properties": {
        "devices": [
            "xx"
        ],
        "url": "https://vzweb08-prod.vz.netgear.com/hmsweb/publish/xx"
    },
    "resource": "subscriptions/xx_web",
    "to": "xx_web",
    "transId": "web!xx"
}
{
    "action": "is",
    "from": "xx",
    "properties": {
        "batteryLevel": 86
    },
    "resource": "cameras/xx",
    "transId": "xx!xx!xx"
}
{
    "action": "is",
    "from": "xx",
    "properties": {
        "motionDetected": true
    },
    "resource": "cameras/xx",
    "transId": "xx!xx!xx"
}
{
    "action": "is",
    "from": "xx",
    "properties": {
        "activityState": "alertStreamActive",
        "dateStarted": -960758195
    },
    "resource": "cameras/xx",
    "transId": "xx!xx!xx"
}
{
    "action": "is",
    "from": "xx",
    "properties": {
        "activityState": "idle",
        "dateStarted": -960728361,
        "stateChangeReason": {
            "code": 4200,
            "message": "The stream was stopped intentionally."
        }
    },
    "resource": "cameras/xx",
    "transId": "xx!xx!xx"
}
{
    "action": "is",
    "from": "xx",
    "properties": {
        "motionDetected": false
    },
    "resource": "cameras/xx",
    "transId": "xx!xx!xx"
}`

**Comment by jeffreydwalter** [comment]
@phr0st, awesome. So you are receiving the motion events.

You can see it here:
```
{ "action": "is", "from": "xx", "properties": { "motionDetected": true }, "resource": "cameras/xx", "transId": "xx!xx!xx" }
```

The value of the motionDetected property is "true"and not "True". I assume that is because of the json.dump. Did you generate that output using print() or the pp() I provided?

**Comment by jlt24** [comment]
OK I did a git pull and only update was arlo-motiondetect.py. 
This is running on a raspberry pi 

output of pip freeze
MySQL-python==1.2.3
Pillow==2.6.1
Unidecode==0.04.16
argparse==1.2.1
chardet==2.3.0
colorama==0.3.2
html5lib==0.999
monotonic==1.4
pexpect==3.2
pygobject==3.14.0
python-apt==0.9.3.12
requests==2.4.3
six==1.8.0
sseclient==0.0.18
urllib3==1.9.1
wsgiref==0.1.2


output from script
{
    "createdDate": "20171116",
    "deviceId": "XXXXXXXXXXXXXX",
    "mediaObjectCount": 3,
    "ownerId": "1XXXXXXXXXXXXXX",
    "presignedContentUrl":   "https://arlos3-prod-z2.s3.amazonaws.com/74D/recordings/1510888XXXXXXXXXXXXXXXXX7&Signature=aPXXXXXXXXXD",
    "presignedLastImageUrl": "https://arlos3-prod-z2.s3.amazonaws.com/c4D/recordings/15XXXXXXXXXXXXX_thumb.jpg?xaT3HFT2IFkNkhx%3D",
    "presignedThumbnailUrl": "https://arlos3-prod-z2.s3.amazonaws.com/c4/119/484D/recordings/1510_thumb.jpg?C2A&Expires=15&Signature=3%4%3D",
    "resource": "mediaUploadNotification",
    "uniqueId": "XXX-XXXXXXXXXXXXXX"
}
{
    "action": "is",
    "from": "XXXXXXXXXXXXXX",
    "properties": {
        "devices": [
            "XXXXXXXXXXXXXX"
        ],
        "url": "https://vzweb04-prod.vz.netgear.com/hmsweb/publish/48XXXXXXXXXXXXXXXXXXXXXXXXXXXXXb"
    },
    "resource": "subscriptions/XXX-XXXXXXXXXXXX_web",
    "to": "XXX-XXXXXXXXXXXX_web",
    "transId": "web!2166cdaf.4iuyde078150"
}
{
    "action": "is",
    "from": "XXX-XXXXXXXXXXXX",
    "properties": {
        "motionDetected": true
    },
    "resource": "cameras/4XXX-XXXXXXXXXXXX4",
    "transId": "XXX-XXXXXXXXXXXX!4fbXXX-XXXXXXXXXXXX6"
}

**Comment by Anton-Schuster** [comment]
I used the script you provided with pp() function.

**Comment by jeffreydwalter** [comment]
@phr0st @jlt24 thanks for providing that. From everything I see you ARE receiving motion events.

I just tested a simple script:
```
from Arlo import Arlo
import json

USERNAME = 'xxxxxxxxxxx'
PASSWORD = 'xxxxxxxxxxx'

arlo = Arlo(USERNAME, PASSWORD)

basestations = arlo.GetDevices('basestation')

def callback(arlo, basestation, event):
    print("motion event detected!")

print("Subscribing To Motion Events")
arlo.SubscribeToMotionEvents(basestations[0], callback)
```

and it works fine for me:
```
$ python ArloTest.py 
Subscribing To Motion Events
motion event detected!
```

You can put print statements inside the SubscribeToMotionEvents and HandleEvents methods inside Arlo.py to debug further: (**replace those two functions with this code and try again**)
```
    def SubscribeToMotionEvents(self, basestation, callback, timeout=None):
        print("inside SubscribeToMotionEvents")
        def callbackwrapper(self, basestation, event):
            print("inside callbackwrapper")
            print(event)
            print(event.get('properties', {}))
            print(event.get('properties', {}).get('motionDetected')):
            if event.get('properties', {}).get('motionDetected'):
                print("motion detected")
                callback(self, basestation, event)

        self.HandleEvents(basestation, callbackwrapper, timeout)

    # Use this method to subscribe to the event stream and provide a callback that will be called for event event received.
    # This function will allow you to potentially write a callback that can handle all of the events received from the event stream.
    def HandleEvents(self, basestation, callback, timeout=None):
        if not callable(callback):
            raise Exception('The callback(self, basestation, event) should be a callable function!')

        basestation_id = basestation.get('deviceId')

        self.Subscribe(basestation)
        print("subscribed to basestation events")
        if basestation_id in self.event_streams and self.event_streams[basestation_id].connected and self.event_streams[basestation_id].registered:
            print("connected to basestation stream")
            while basestation_id in self.event_streams and self.event_streams[basestation_id].connected:
                event = self.event_streams[basestation_id].Get(block=True, timeout=timeout)
                if event:
                    print("got event")
                    callback(self, basestation, event)
```

**Comment by jlt24** [comment]
Just a quick update.  I have not yet done your latest suggestion but I did set this up on another machine and it works as is.  I will modify arlo.py with the above code and let you know.

Thanks for your help!!!!

**Comment by Anton-Schuster** [comment]
today i tested your "event test" script again and found out that not all events are triggered. i had 10 notifications from motion events on my mobile phone. but only 2 of them were triggered by the script. i also noticed that after some other events only mediaupload events are triggered by the script. can you reproduce that?

**Comment by jeffreydwalter** [comment]
@phr0st the test script doesn't trigger the events. It merely subscribes to the arlo server, which pushes the events to the script. I have not been able to reproduce the issues you report. I am going to be away from my cameras for the holidays, so I will not be able to attempt to do any more testing until next weekend. 
It would be really helpful if you could paste the exact code (even if it's the code I gave you) and the exact output along with a detailed list of steps you are taking to reproduce the issue.

**Comment by saultenuts** [comment]
Hi, this doesn't seem to work with the new Arlo Q.  The Arlo Q is a standalone (wired) camera without a basestation.  So when calling:
`basestations = arlo.GetDevices('basestation')`
an empty list is returned and nothing works after that.  
Even using:
`arlo.SubscribeToMotionEvents(device_id, xcloud_id, callback)`
I get an error:
`>>> arlo.SubscribeToMotionEvents(device_id, xcloud_id, callback)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chrome/Python/Arlo/Arlo.py", line 346, in SubscribeToMotionEvents
    self.HandleEvents(basestation, callbackwrapper, timeout)
  File "/home/chrome/Python/Arlo/Arlo.py", line 354, in HandleEvents
    basestation_id = basestation.get('deviceId')
AttributeError: 'str' object has no attribute 'get'
`

Any thoughts on how to modify to reference just the camera without a basestation?

**Comment by jeffreydwalter** [comment]
@saultenuts looks like you are using the 0.9 version of the library with the old api. If you're not heavily invested in that version, you should pull the master branch.

With Arlo Q, you should pass a camera since you don't have a basestation. The cameras _are_ their own basestation.

So, with the Arlo Q, you would do something like:
```
from Arlo import Arlo
  
USERNAME = 'user@example.com'
PASSWORD = 'supersecretpassword'

try:

    # Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
    # Subsequent successful calls to login will update the oAuth token.
    arlo = Arlo(USERNAME, PASSWORD)
    # At this point you're logged into Arlo.

    cameras = arlo.GetDevices('camera')

    # Define a callback function that will get called once for each motion event.
    def callback(arlo, camera, event):
        # Here you will have access to self, basestation_id, xcloud_id, and the event schema.
        print("motion event detected!")
        #print(event)
        #print(arlo)

    # Subscribe to motion events. This method blocks until the event stream is closed. (You can close the event stream in the callback if you no longer want to listen for events.)
    arlo.SubscribeToMotionEvents(cameras[0], callback)
except Exception as e:
    print(e)
```

**Comment by lundpetersen** [comment]
@jeffreydwalter - I just tried your example for Arlo Q - but it doesn't work for me. I have a mix of multiple Arlo Q and multiple Arlo Pro (at the moment only one basestation, but I plan on attaching one more).
It seems like your example only returns the 2 Arlo pro cameras that is connected to my base, and not the 2 Arlo cams. Any thoughts or ideas?

**Comment by jeffreydwalter** [comment]
Oh right, I believe the device type is "arloq" and/or "arloqs".

I don't have any of those, so I haven't really tested the library in that regard.

If you don't mind, it would be tremendously helpful if you could send me the output of this call:
```
from Arlo import Arlo
  
USERNAME = 'user@example.com'
PASSWORD = 'supersecretpassword'

def pp(data):
    print(json.dumps(data, indent=4, sort_keys=True))

try:

    # Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
    # Subsequent successful calls to login will update the oAuth token.
    arlo = Arlo(USERNAME, PASSWORD)
    # At this point you're logged into Arlo.

    pp(arlo.GetDevices())
except Exception as e:
    print(e)
```
Try:
```
from Arlo import Arlo
  
USERNAME = 'user@example.com'
PASSWORD = 'supersecretpassword'

try:

    # Instantiating the Arlo object automatically calls Login(), which returns an oAuth token that gets cached.
    # Subsequent successful calls to login will update the oAuth token.
    arlo = Arlo(USERNAME, PASSWORD)
    # At this point you're logged into Arlo.
    
    cameras = arlo.GetDevices('arloq')
    # Or you might have to use "arloqs".
    # cameras = arlo.GetDevices('arloqs')

    # Define a callback function that will get called once for each motion event.
    def callback(arlo, camera, event):
        # Here you will have access to self, basestation_id, xcloud_id, and the event schema.
        print("motion event detected!")
        #print(event)
        #print(arlo)

    # Subscribe to motion events. This method blocks until the event stream is closed. (You can close the event stream in the callback if you no longer want to listen for events.)
    arlo.SubscribeToMotionEvents(cameras[0], callback)
except Exception as e:
    print(e)
```

**Comment by jeffreydwalter** [comment]
Closing due to age.
